[[pages]]
path = "index.py"
name = "Ğ§Ğ°Ñ‚-Ğ±Ğ¾Ñ‚"
icon = "ğŸ’¬"

[[pages]]
path = "pages/rag.py"
name = "Ğ Ğ°Ğ±Ğ¾Ñ‚Ğ° Ñ ĞĞŸĞ"
icon = "ğŸ’¾"

[[pages]]
path = "pages/file_q&a.py"
name = "Ğ—Ğ°Ğ³Ñ€ÑƒĞ·ĞºĞ° Ğ´Ğ¾ĞºÑƒĞ¼ĞµĞ½Ñ‚Ğ¾Ğ²"
icon = "ğŸ“–"

